name: Build & Copy Laravel Public Assets

on:
  push:
    branches:
      - main

jobs:
  build-and-copy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # penting agar bisa commit dan push

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, bcmath, intl, pdo, curl
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install NPM Dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Build Assets
        run: npm run build

      - name: Copy `public/build` to Root
        run: |
          mkdir -p ./build
          cp -r public/build/* ./build/

      - name: Commit and Push Build Assets
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build/
          git commit -m "chore: update build assets [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main

